### ISSUE TITLE
Feature request => Add Tap, Motion, and Freefall

### ISSUE THREAD

**Issue by appl044** [adafruit/Adafruit_CircuitPython_MPU6050#11]
@siddacious Bryan, thank you for posting your code and helping us.
Adafruit_CircuitPython_ADXL34x  Tap, Motion and Freefall are solid examples within this other github.

Could this be possibly considered for the MPU6050 also, to be added within the examples?

**Comment by siddacious** [comment]
The Tap, Motion, and Freefall features of the ADXL34x sensors is supported directly by the hardware itself; the MPU6050 does not have that capability so unfortunately we can't add it here
