### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Rakesh199524** [adafruit/Adafruit_CircuitPython_MPU6050#19]
import time
import adafruit_mpu6050
import board

i2c = board.I2C()# uses board.SCL and board.SDA
mpu = adafruit_mpu6050.MPU6050()

while True:
    print("Acceleration: X:%.2f, Y: %.2f, Z: %.2f m/s^2"%(mpu.acceleration))
    print("Gyro X:%.2f, Y: %.2f, Z: %.2f degrees/s"%(mpu.gyro))
    print("Temperature: %.2f C"%mpu.temperature)
    print("")
    time.sleep(1)

i m using this code for raspberry pi pico but its showing "  File "<stdin>", line 3, in <module>
ImportError: no module named 'board'"

**Comment by ladyada** [comment]
you could be using micropython instead of circuitpython. if you have more questions, please post to the forums or visit discord!
