### ISSUE TITLE
Orientation? Compass Heading?

### ISSUE THREAD

**Issue by KingFuGitHub** [adafruit/Adafruit_CircuitPython_MPU6050#25]
I'm wondering if we can use the mpu6050 as a compass with a heading that can tell direction.

**Comment by mlg556** [comment]
I think that requires a separate magnetometer/compass. The datasheet states that you can connect a third party magnetometer module to the "Auxiliary I2C", and the 6050 can act as a I2C master to read from that module.

**Comment by FoamyGuy** [comment]
Closing this, not an issue with the library.
