### ISSUE TITLE
MemoryError when loading module

### ISSUE THREAD

**Issue by explody** [adafruit/Adafruit_CircuitPython_MPU6050#36]
Using an Adafruit Metro Express M0, CircuitPython 8.2.8, and MPU boards from Amazon, with or without having an MPU board connected, I get an. immediate memory error upon loading the module:

```
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== import time
=== import board
=== import digitalio
=== import adafruit_mpu6050
=== 
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "adafruit_mpu6050.py", line 45, in <module>
  File "adafruit_register/i2c_bits.py", line 25, in <module>
MemoryError: memory allocation failed, allocating 60 bytes
>>>
```

The boards in question do work if I use C - is the M0 just not beefy enough, maybe?

**Comment by dhalbert** [comment]
The SAMD21 on the Metro M0 only has 32kB of RAM. This library is probably too big. You could try trimming down the source code to remove things you don't need. Are you loading the .py or the .mpy version? The .mpy version will not require on-board compilation, and that _might_ help. But the SAMD21 boards have issues with larger pieces of code.
